# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-21 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('max_price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('update_quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_of_payment', models.CharField(choices=[('UPI', 'UPI Mode'), ('CASH', 'Cash Payment'), ('CARD', 'Card Payment')], max_length=50)),
                ('customer_concerned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionProductMapper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.Product')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.Transaction')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='products_selected',
            field=models.ManyToManyField(through='billing.TransactionProductMapper', to='billing.Product'),
        ),
    ]
