# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-22 05:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='update_quantity',
            new_name='updated_quantity',
        ),
    ]
